style"frame"{
xthickness=2
ythickness=4
engine"pixmap"{
image{
function=SHADOW_GAP
shadow=IN
file="images/frame-in-gap.svg"
border={6,6,6,6}
stretch=TRUE
gap_start_file="images/frame-in-gap-start.svg"
gap_start_border={6,0,4,0}
gap_end_file="images/frame-in-gap-end.svg"
gap_end_border={0,6,0,4}
gap_file="images/none.svg"}
image{
function=SHADOW_GAP
shadow=ETCHED_IN
file="images/frame-in-gap.svg"
border={4,4,6,4}
stretch=TRUE
gap_start_file="images/frame-in-gap-start.svg"
gap_start_border={6,0,4,0}
gap_end_file="images/frame-in-gap-end.svg"
gap_end_border={0,6,0,4}
gap_file="images/none.svg"}
image{
function=SHADOW_GAP
shadow=OUT
file="images/frame-out-gap.svg"
border={6,6,6,6}
stretch=TRUE
gap_start_file="images/frame-out-gap-start.svg"
gap_start_border={6,0,4,0}
gap_end_file="images/frame-out-gap-end.svg"
gap_end_border={0,6,0,4}
gap_file="images/none.svg"}
image{
function=SHADOW_GAP
shadow=ETCHED_OUT
file="images/frame-out-gap.svg"
border={4,4,6,4}
stretch=TRUE
gap_start_file="images/frame-out-gap-start.svg"
gap_start_border={6,0,4,0}
gap_end_file="images/frame-out-gap-end.svg"
gap_end_border={0,6,0,4}
gap_file="images/none.svg"}
image{
function=SHADOW
shadow=IN
file="images/frame-in.svg"
border={10,10,10,10}
stretch=TRUE}
image{
function=SHADOW
shadow=ETCHED_IN
file="images/frame-in.svg"
border={10,10,10,10}
stretch=TRUE}
image{
function=SHADOW
shadow=OUT
file="images/frame-out.svg"
border={10,10,10,10}
stretch=TRUE}
image{
function=SHADOW
shadow=ETCHED_OUT
file="images/frame-out.svg"
border={10,10,10,10}
stretch=TRUE}}}
class"GtkFrame"style"frame"
