style"scale"{
xthickness=0
ythickness=0
GtkRange::slider-width=36
GtkScale::slider-length=36
GtkScale::trough-side-details=0
GtkRange::trough-border=0
GtkRange::activate-slider=0
engine"pixmap"{
image{
function=BOX
orientation=HORIZONTAL
file="images/scale-horizontal.svg"
border={18,18,18,18}
stretch=TRUE}
image{
function=BOX
orientation=VERTICAL
file="images/scale-vertical.svg"
border={18,18,18,18}
stretch=TRUE}
image{
function=SLIDER
state=NORMAL
file="images/colorspecific/scale-slider-bg-active.svg"
stretch=TRUE
overlay_file="images/scale-slider.svg"
overlay_border={16,16,16,16}
overlay_stretch=TRUE}
image{
function=SLIDER
state=PRELIGHT
file="images/colorspecific/scale-slider-bg-active.svg"
stretch=TRUE
overlay_file="images/scale-slider.svg"
overlay_border={16,16,16,16}
overlay_stretch=TRUE}
image{
function=SLIDER
state=SELECTED
file="images/colorspecific/scale-slider-bg-active.svg"
stretch=TRUE
overlay_file="images/scale-slider.svg"
overlay_border={16,16,16,16}
overlay_stretch=TRUE}
image{
function=SLIDER
state=ACTIVE
file="images/colorspecific/scale-slider-bg-active.svg"
stretch=TRUE
overlay_file="images/scale-slider.svg"
overlay_border={16,16,16,16}
overlay_stretch=TRUE}
image{
function=SLIDER
state=INSENSITIVE
file="images/colorspecific/scale-slider-bg.svg"
stretch=TRUE
overlay_file="images/scale-slider.svg"
overlay_border={16,16,16,16}
overlay_stretch=TRUE}}}
class"GtkScale"style"scale"

